language: ruby
rvm:
- 2.3.3

before_script:
 - bundle install

script:
- bundle exec jekyll build
- mkdir site
- cd site
- git init
- git remote add origin https://$GH_TOKEN@github.com/kylemhall/kylehall.info
- git fetch origin
- git checkout origin/gh-pages
- cp -r ../_site/* .
- git add *
- git commit -a -m "Update from master"
- git push origin HEAD:refs/heads/gh-pages

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
