language: ruby
rvm:
- 2.3.3

before_script:
 - bundle install

script:
- bundle exec jekyll build
- cd _site
- git init
- git add *
- git commit -a -m "Update from master"
- git remote add github https://$GH_TOKEN@github.com/kylemhall/kylehall.info
- git push github HEAD:gh-pages

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
